version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5001:8080" # just for testing on localhost
    volumes:
      - data_volume:/opt/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443/api/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  backend_network:

volumes:
  data_volume:
